Repository WordPress/wp-autoupdates, pull requests merged in 2020-03, with the labels that each got.

#29 Remove features / to-do list from readme.md
  readme.md
Labels: documentation

#35 i18n: Merge similar translation strings
  wp-autoupdates.php
Labels: i18n

#36 Handle both themes and plugins email notifications
  wp-autoupdates.php
Labels: enhancement

#33 Add and populate Automatic updates column, add and handle enable/disable auto-updates bulk actions to the multisite themes list table.
  wp-autoupdates.php
Labels: enhancement

#32 Avoid duplicate Updating... dialog
  wp-autoupdates.php
Labels: bug

#37 Change plugin structure to ensure it can self-deactivate when the feature is merged into Core
  functions.php
  wp-autoupdates.php
Labels: Core Merge Prerequisite
