Repository WordPress/wp-autoupdates, pull requests merged in 2020-04, with the labels that each got.

#57 Add filters and constant to allow developers to disable plugins and themes autoupdate email notifications
  functions.php
Labels: Core Merge Prerequisite, enhancement

#62 Documentation: Improve DocBlocks.
  functions.php
Labels: documentation

#60 I18n - Merge with similar string
  functions.php
Labels: i18n

#54 Switch disable link to red on Multisite Themes Screen
  css/wp-autoupdates.css
Labels: bug, design

#70 Remove green and red colors on texts and links
  css/wp-autoupdates.css
Labels: design

#73 Fix documentation and comment standards.
  functions.php
Labels: documentation

#74 Remove dashicons from the UI
  css/wp-autoupdates.css
  functions.php
Labels: design

#68 Don't display the Enable/Disable link in the Theme Details modal on a subsite in multisite.
  functions.php
Labels: bug

#76 Remove Automatic Updates column from the Network Admin > Sites > Edit > Themes screen
  functions.php
Labels: bug

#75 Replace "Enable" string with "Enable auto-updates"
  functions.php
Labels: design

#78 Replace Disable strings with Disable auto-updates
  functions.php
Labels: design

#77 Update confirmation message wording
  functions.php
Labels: design

#61 Add Ajax to Plugin and Themes Screen
  css/wp-autoupdates.css
  functions.php
  js/wp-autoupdates.js
Labels: enhancement

#85 Accessibility: Communicate AJAX enabling/disabling changes to screen readers
  functions.php
  js/wp-autoupdates.js
Labels: a11y, bug

#90 Add Better Handling to Ajax Errors
  functions.php
  js/wp-autoupdates.js
Labels: bug

#91 Prevent CSS from being enqueued on sub-site plugins & themes screens in multisite.
  functions.php
Labels: bug
