Repository WordPress/wp-autoupdates, pull requests merged in 2020-05, with the labels that each got.

#96 Ensure disabling via AJAX doesn't result in errors of the link is clicked multiple times while processing is still happening.
  functions.php
Labels: a11y, bug

#103 Simplifies Ajax on both the JS and PHP sides.
  css/wp-autoupdates.css
  functions.php
  js/wp-autoupdates.js
Labels: Core Merge Prerequisite, a11y, design, enhancement

#109 Various i18n fixes/optimizations
  functions.php
Labels: i18n

#112 Remove constants from the feature plugin
  functions.php
Labels: Core Merge Prerequisite

#117 I18n - Remove unnecessary concatenation.
  functions.php
Labels: i18n

#121 Add help tabs on update-core, plugins, and themes admin screens
  functions.php
Labels: documentation, enhancement

#125 Remove auto-updates options when plugin is uninstalled
  wp-autoupdates.php
Labels: Core Merge Prerequisite, enhancement

#128 bump version number for 0.8.0
  package-lock.json
  package.json
  readme.txt
  wp-autoupdates.php
Labels: task

#131 Prevent multiple simultaneous requests
  js/wp-autoupdates.js
Labels: enhancement

#130 Fix incorrect admin notice text when auto-updates are enabled for a plugin when JS is not enabled in the browser
  functions.php
  js/wp-autoupdates.js
Labels: bug

#132 Strip plugins/themes that have been deleted from the site options just before they are updated
  functions.php
Labels: enhancement

#133 Copy the plugin's site options to core's site options on self-deactivation
  wp-autoupdates.php
Labels: enhancement

#136 Version 0.8.1
  package-lock.json
  package.json
  readme.md
  readme.txt
  wp-autoupdates.php
Labels: task

#138 Remove unnecessary translatable strings
  functions.php
Labels: i18n
